### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adrianinsaval** [comment]
can we do qt6 as a variant but still use qt5 for the default build? I'm hesitant about publishing with qt6 if we can avoid it. It has had very little testing and I believe there are still unresolved bug when using qt6. The development team had decided because of this to stick with qt5 for 1.0.0 and target 1.1.0 for the qt6 transition and I would prefer to not go against that.

To get it to to solve the environment I had to make new vtk and pcl builds with qt5 though

**Comment by looooo** [comment]
Hi adrian, I would like to offer both qt5/qt6 via two seperated branches. So  keeping qt6 as the main branch and creating a new qt5 branch which basically mirrors the freecad/freecad-feedstock main branch. Keeping them both in the same branch adds too much overhead in my eyes. It's easier to keep the qt6-branch updated with the latest migrations (py3.13...) I don't think py3.12 support for pyside2 is coming soon, so at one point the qt5-branch will be outdated. But as it has been proven, we still can build the qt5 branch with older dependencies for some time. Is this approch ok for you?

**Comment by adrianinsaval** [comment]
That would be ok, how would one choose which to use at installation?

**Comment by looooo** [comment]
> Congratulations on this huge milestone! 🥳

thanks @h-vetinari, this wouldn't be possible without your help and the help of all the people from conda-forge. And for sure all the great work developer do for FreeCAD and all the maintainers. Especially thanks to @oursland and @adrianinsaval who do a fantastic job.

**Pull request merged**
