### PR TITLE
build 0.18b for Python 3.7

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

this should go into a branch called `0.18b`.

There is a pretty annoying bug that was introduced (see [this discussion](https://forum.freecadweb.org/viewtopic.php?f=3&t=36711)) after 0.18b which breaks https://github.com/Microsoft/qmt and the downstream (private) packages for Python 3.7.

### CODE REVIEW

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
Not sure what you are going to try here. Updating boost needs some more work here:https://github.com/conda-forge/coin3d-feedstock/pull/14
For qt5.9 everything should be ready, but I am currently testing the builds and see some crashes... You can install 0.19 development packages via channel freecad/label/dev (qt.5.6) and via channel freecad/label/testing (qt.5.9)

**Comment by basnijholt** [comment]
@looooo, thanks for taking a look!

I am merely trying to build 0.18b for Python 3.7 because that still had Open Cascade 7.2.0.

Unfortunately, we need that version of Open Cascade because of [this bug](https://tracker.dev.opencascade.org/view.php?id=30760).

OTOH it might be possible to build 0.18 with Open Cascade 7.2.0 too, but probably you understand that a whole lot better than I do. Do you think that's possible?

**Comment by looooo** [comment]
This sounds like a very difficult task. I guess the easiest way to get this done is:
- build occt 7.2 with latest tools
- build netgen with occt 7.2
- build smesh with occt7.2 and netgen
- build freecad with occt7.2 and d esh

I don't think using older builds will work out of the box. At least this is not something I would like to work on. No chance this can be fixed by a patch?

**Comment by looooo** [comment]
I tried to build freecad with occt7.2 but failed with:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - occt=7.2
  - python=3.7
  - smesh
```
https://circleci.com/gh/looooo/freecad-feedstock/290

So the problem here is that smesh-occt7.2-python3.7 and netgen-occt7.2-python3.7 is missing. So at least netgen, smesh and freecad have to be rebuild. I guess the easier solution is using python3.6 + occt7.2 for now and try to get the issue fixed in the next occt-release.

**Comment by basnijholt** [comment]
@looooo, actually [there is a patch now](http://git.dev.opencascade.org/gitweb/?p=occt.git;a=blobdiff;f=src/BOPTools/BOPTools_AlgoTools2D_1.cxx;h=aca558d7a559bce000887e366a5d44a60475d474;hp=f4d2e3029264c726d5d9f12754fac2a1bb2f2c74;hb=68fce0db696b6bf04765e52cbb080efd3ab9845c;hpb=b30b2c138115dead85f5151446bac8636c2cf130)! 

If I apply it to occt, I would need to rebuild, netgen, then smesh, and then FreeCAD, is that right?

**Comment by looooo** [comment]
Hmmm, I guess it's best to try first locally if only rebuilding occt works already.

**Pull request closed without merging**
