### PR TITLE
update to new-compilers

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

* [ ] wait for 0.18 release
* [ ] maybe wait for vtk8.2.0

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
I don't think this is the solution but I'll try it anyway:
@conda-forge-admin, please update circle

**Comment by looooo** [comment]
thanks @chrisburr for having a look at this

not triggered builds for circle-ci is one problem, but with azure there are reported more problems:
win: `LINK : warning LNK4044: unrecognized option '/lpthreads'; ignored` -> __no idea, help needed__
linux: OPENGL_gl_LIBRARY not found -> __need additional yum requirements__
osx: patch not applyable -> __osx.patch can be removed__

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
try to reopen the PR

**Pull request closed without merging**
