### PR TITLE
Add fmt dependency

### PR DESCRIPTION
**Pull request by adrianinsaval**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adrianinsaval** [comment]
it seems fmt is being installed by some other package so freecad is using the shared library instead of building it's own static version, this means you need to install fmt along side freecad for it to run properly

**Comment by adrianinsaval** [comment]
@conda-forge-admin, please rerender

**Comment by adrianinsaval** [comment]
how can I find out what else is pulling fmt when building freecad?

**Comment by looooo** [comment]
> how can I find out what else is pulling fmt when building freecad?

is there anything else pulling fmt? and why do we have to pin it so strict?

**Comment by adrianinsaval** [comment]
> is there anything else pulling fmt?

yes, fmt was being pulled during build but not when installing freecad which caused problems. See https://forum.freecad.org/viewtopic.php?p=670177

> and why do we have to pin it so strict?
recently there was an update of fmt to 10 on conda, that was causing problem on bundles so I pinned to what was working before. I don't know how strict it really needs to be. Is there a way to make it pin whatever version is used during build? I think this is actually dependent on what version is actually pulled during build.

> but it's interesting that the linux-aarch64 builds work with this pr. Did you made any other changes?

I did not even notice that! Nice side effect.

**Pull request merged**
