### PR TITLE
update to 0.21.0

### PR DESCRIPTION
**Pull request by adrianinsaval**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adrianinsaval** [comment]
@looooo it seems python 3.11 is not automatically enable, should we enable it? if yes, how?

**Comment by adrianinsaval** [comment]
I'm also not seeing arm64/aarch64 builds, how to enable?

**Comment by looooo** [comment]
@adrianinsaval we need to include the migration files

**Comment by adrianinsaval** [comment]
JFYI official release will be made from the freecad channel: https://github.com/FreeCAD/freecad-feedstock/runs/15540924989

but I would like to get it on conda-forge too eventually, with more python version variety for whoever needs them.

occt I don't think it's a good idea to use >7.6.3 yet, there's some pretty serious incompatibilities that still need to be addressed

about other packages, no clue.

**Comment by adrianinsaval** [comment]
also @looooo if you have time now could you look into this? https://github.com/conda-forge/libspnav-feedstock/commit/e745bdf8faa8c1d2ee693fb5deac5d45b162d40f#commitcomment-121104281 and corresponding PR https://github.com/conda-forge/libspnav-feedstock/pull/5 it would be nice to be able to ship a newer version of spnav with the appimage

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
