### PR TITLE
another time try to fix linux and osx

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
Power cycling for missing CI (macOS and Linux).

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Would try the things in the "Otherwise (e.g. in a PR to staged-recipes)..." below.

ref: https://conda-forge.org/docs/ciservices.html#enabling-circle-on-your-fork

**Comment by looooo** [comment]
@jakirkham  I guess the problem is that I previously tried to setup a freecaed-feedstock to build packages for another channel.

**Comment by jakirkham** [comment]
Ah ok. That makes sense. Glad things are working now.

**Pull request merged**
