### PR TITLE
rebuild FreeCAD

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by basnijholt** [comment]
Rebuilding with the new build of occt, see https://github.com/conda-forge/occt-feedstock/pull/30.

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
I don't think this is necessary. Simple update occt in your env.

**Comment by looooo** [comment]
To get freecad updated to latest pinnings (conda-forge-pinnings) we need to rebuild coin and smesh against booct-cpp 1.70. This still needs some work:
https://github.com/conda-forge/coin3d-feedstock/pull/14
https://github.com/conda-forge/smesh-feedstock/pull/24

**Comment by looooo** [comment]
FreeCAD 0.18.3 is rebuild with latest deps. I guess we can close this one. Feel free to reopen if this isn't the case. #26

**Pull request closed without merging**
