### PR TITLE
dev-branch, boost 1.78, python3.11, vtk 9.2, linux-aarch64, osx-arm64, occt 7.7, pcl 1.13

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
osx-arm: 
```
The reported errors are:
- Encountered problems while solving:
-   - package pcl-1.11.1-h70a416a_4 requires vtk >=9.0.1,<9.0.2.0a0, but none of the providers can be installed
```

**Comment by basnijholt** [comment]
Thanks a lot for working on this!

**Comment by looooo** [comment]
@wwmayer can you help with the windows issue? Is this due to the boost update?

**Comment by looooo** [comment]
> If I got it right then you have upgraded to boost 1.78 and now you run into a build failure when compiling LuxTools.cpp.
> 
> Now boost/regex.hpp is also included in FreeCADBase and FreeCADApp. Apparently this compiles fine because the two libs are built before Raytracing. So, I assume the failure must be caused by some different/missing defines and when comparing the CMakeLists.txt of FreeCADBase and Raytracing then the latter lacks of:
> 
> ```
> if(WIN32)
>     add_definitions(-DBOOST_DYN_LINK)
> endif(WIN32)
> ```
> 
> Does adding it to FreeCAD/src/Mod/Raytracing/App/CMakeLists.txt solve the failure?

thanks for your help!
I tried this. But the issue seems to be still the same.

**Comment by looooo** [comment]
@wwmayer also adding the boost_libraries to the link-libraries didn't solve this issue.

**Comment by wwmayer** [comment]
OK, if this doesn't help it could be a general problem with boost 1.78 and it may occur on other platforms too. I will try to compile this boost version locally on Linux and build FreeCAD with it.

**Comment by wwmayer** [comment]
Using boost 1.78 on Linux works fine. But after re-reading the error message I realized the missing "LCTYPE" type. The line 200 in w32_regex_traits.hpp expects that Windows.h is already included but in fact it isn't. It may help to add `#include <Windows.h>` to src/Mod/Raytracing/App/PreCompiled.h

**Comment by looooo** [comment]
> Using boost 1.78 on Linux works fine. But after re-reading the error message I realized the missing "LCTYPE" type. The line 200 in w32_regex_traits.hpp expects that Windows.h is already included but in fact it isn't. It may help to add `#include <Windows.h>` to src/Mod/Raytracing/App/PreCompiled.h

thanks, I tried this with the last patch update.
Are the precompiled.h files used only for windows?

**Comment by wwmayer** [comment]
> Are the precompiled.h files used only for windows?

At the moment yes but in the future it may be used for other compilers, too.

**Comment by looooo** [comment]
Still the same problem. Did I add the include at a wrong position?

**Comment by wwmayer** [comment]
> Still the same problem. Did I add the include at a wrong position?

Oh, my bad. I just realized that for the Raytracing module we don't use the PCH (Pre-compiled header) option. But when looking at the code of LuxTools.cpp no regular expression are used. So, it would be fine to just remove the line `#include <boost/regex.hpp>`

**Comment by looooo** [comment]
@wwmayer Now the same issue appears in techdraw.

**Comment by looooo** [comment]
@conda-forge/core are there any examples how to cross-compile with vtk-dependency?

**Comment by looooo** [comment]
> @wwmayer Now the same issue appears in techdraw.
adding the windows.h fixed this error. But now there is another issue:

```
C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DCOIN_DLL -DHAVE_SNPRINTF -DPYCXX_6_2_COMPATIBILITY -DSALOME_USE_64BIT_IDS -D_OCC64 -I%SRC_DIR%\build\tests\lib\googlemock\gmock_main_autogen\include -I%PREFIX%\Library\include\smesh -I%SRC_DIR%\build\src -I%SRC_DIR%\src -I%SRC_DIR%\tests\lib\googlemock\include -I%SRC_DIR%\tests\lib\googlemock -I%SRC_DIR%\tests\lib\googletest\include -I%SRC_DIR%\tests\lib\googletest /DWIN32 /D_WINDOWS /W4 /GR  /MP /MD /O2 /Ob2 /DNDEBUG /Zm150 /bigobj /Zi /EHa -GS -W4 -WX -wd4251 -wd4275 -nologo -J -D_UNICODE -DUNICODE -DWIN32 -D_WIN32 -DSTRICT -DWIN32_LEAN_AND_MEAN -wd4702 -utf-8 -DGTEST_HAS_PTHREAD=1 -EHsc -D_HAS_EXCEPTIONS=1  -std:c++17 /showIncludes /Fotests\lib\googlemock\CMakeFiles\gmock_main.dir\__\googletest\src\gtest-all.cc.obj /Fdbin\gmock_main.pdb /FS -c %SRC_DIR%\tests\lib\googletest\src\gtest-all.cc
cl : Command line warning D9025 : overriding '/EHa' with '/EHs'
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(470): error C2065: 'Runnable': undeclared identifier
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(470): error C2065: 'runnable': undeclared identifier
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(471): error C2065: 'thread_can_start': undeclared identifier
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(471): error C2275: 'testing::internal::Notification': illegal use of this type as an expression
%SRC_DIR%\tests\lib\googletest\include\gtest/internal/gtest-port.h(1213): note: see declaration of 'testing::internal::Notification'
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(471): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(472): error C2059: syntax error: ':'
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(473): error C2065: 'runnable': undeclared identifier
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(473): error C2065: 'thread_can_start': undeclared identifier
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(473): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(473): error C2059: syntax error: '{'
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(473): error C2143: syntax error: missing ';' before '{'
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(473): error C2447: '{': missing function header (old-style formal list?)
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(475): error C2027: use of undefined type 'testing::internal::ThreadWithParamBase'
%SRC_DIR%\tests\lib\googletest\include\gtest/internal/gtest-port.h(1252): note: see declaration of 'testing::internal::ThreadWithParamBase'
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(475): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(475): error C3861: 'Join': identifier not found
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(475): warning C4508: 'testing::internal::{dtor}': function should return a value; 'void' return type assumed
%SRC_DIR%\tests\lib\googletest\src/gtest-port.cc(477): error C2027: use of undefined type 'testing::internal::ThreadWithParamBase'
%SRC_DIR%\tests\lib\googletest\include\gtest/internal/gtest-port.h(1252): note: see declaration of 'testing::internal::ThreadWithParamBase'
[2807/3975] Building CXX object tests\CMakeFiles\InventorBuilder_Tests_run.dir\src\InventorBuilder.cpp.obj
[2808/3975] Automatic MOC and UIC for target FreeCADGui
AutoMoc: D:/bld/freecad_1670489173127/work/src/Gui/UiLoader.h(0): Note: No relevant classes found. No output generated.

```

**Comment by wwmayer** [comment]
That affects Google Unit testing framework and I don't know how to fix it. The best what you can do at the moment is to avoid to include the tests directory in the top-level CMakeLists.txt file. To do that replace the very last three lines with:
```
if (BUILD_TEST AND NOT BUILD_WITH_CONDA)
    add_subdirectory(tests)
endif()
```

**Comment by wwmayer** [comment]
Here the reasons why Windows.h is not included any more by w32_regex_traits.hpp: https://github.com/boostorg/regex/pull/158

**Comment by looooo** [comment]
something is still wrong with techdraw. I still get the same boost error.

**Comment by wwmayer** [comment]
To avoid to adjust all includes of boost/regex.hpp it's probably best to create a file boost_regex.hpp that includes the former file and for boost >= 1.78 Windows.h. In the client code we then include boost_regex.hpp.

**Comment by looooo** [comment]
@wwmayer seems like the boost problem in tech-draw is still there.

**Comment by wwmayer** [comment]
OK, then there is no way other than testing it explicitly with boost 1.78 on Windows...

**Comment by wwmayer** [comment]
I have tried boost 1.78 on Windows now and the TechDraw module compiles fine.

**Comment by looooo** [comment]
I am now trying to build freecad with pch enabled, but I get this error:
```
2022-12-13T17:27:23.5043542Z %SRC_DIR%\src\Mod\Fem\App\PreCompiled.h(83): fatal error C1083: Cannot open include file: 'SMDS_PolyhedralVolumeOfNodes.hxx': No such file or directory
```

seems to be an issue with smesh.

**Comment by wwmayer** [comment]
I think you are using the external smesh. I assume the file doesn't exist any more in newer smesh versions.
When looking at the code where SMDS_PolyhedralVolumeOfNodes.hxx is included then it's only that PreCompiled.h where you see this error.  So, it's fine to just remove this line.

**Comment by looooo** [comment]
thanks @wwmayer , now I get this error:
```
2022-12-16T16:37:36.0950847Z %SRC_DIR%\src\Mod\MeshPart\App\PreCompiled.h(52): fatal error C1083: Cannot open include file: 'boost/python.hpp': No such file or directory
```

but I don't see this line in the freecad-src.

**Comment by looooo** [comment]
ok, found the issue. it was introduced recently:
https://github.com/FreeCAD/FreeCAD/pull/7979

**Comment by looooo** [comment]
Remaining errors:
```
FAILED: src/Mod/TechDraw/App/CMakeFiles/TechDraw.dir/DrawUtil.cpp.obj 
C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DFCAppTechDraw -DHAVE_ACOSH -DHAVE_ASINH -DHAVE_ATANH -DHAVE_SNPRINTF -DMOD_TECHDRAW_HANDLE_FACES=1 -DPYCXX_6_2_COMPATIBILITY -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DSALOME_USE_64BIT_IDS -DTechDraw_EXPORTS -D_OCC64 -D_PreComp_ -I%SRC_DIR%\build\src\Mod\TechDraw\App\TechDraw_autogen\include -I%PREFIX%\Library\include\smesh -I%SRC_DIR%\build\src -I%SRC_DIR%\src -I%SRC_DIR%\build -I%SRC_DIR%\build\src\Mod\TechDraw\App -I%SRC_DIR%\src\Mod\TechDraw\App -I%PREFIX%\Library\include -I%PREFIX%\Library\include\opencascade -I%PREFIX%\include -external:I%PREFIX%\Library\include\qt -external:I%PREFIX%\Library\include\qt\QtXmlPatterns -external:I%PREFIX%\Library\include\qt\QtNetwork -external:I%PREFIX%\Library\include\qt\QtCore -external:I%PREFIX%\Library\.\mkspecs\win32-msvc -external:I%PREFIX%\Library\include\qt\QtConcurrent -external:I%PREFIX%\Library\include\qt\QtXml -external:W0 /DWIN32 /D_WINDOWS /W3 /GR  /MP /MD /O2 /Ob2 /DNDEBUG /Zm150 /bigobj /Zi /EHa -std:c++17 /Yu"PreCompiled.h" /FI"D:/bld/freecad_1671212959959/work/build/src/Mod/TechDraw/App/TechDraw.pch" /Fp"D:/bld/freecad_1671212959959/work/build/src/Mod/TechDraw/App/TechDraw.pch" /showIncludes /Fosrc\Mod\TechDraw\App\CMakeFiles\TechDraw.dir\DrawUtil.cpp.obj /Fdsrc\Mod\TechDraw\App\CMakeFiles\TechDraw.dir\ /FS -c %SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): warning C4002: too many arguments for function-like macro invocation 'min'
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2589: '(': illegal token on right side of '::'
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2062: type 'unknown-type' unexpected
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2143: syntax error: missing ';' before '{'
FAILED: src/Mod/TechDraw/App/CMakeFiles/TechDraw.dir/DrawUtil.cpp.obj 
C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DFCAppTechDraw -DHAVE_ACOSH -DHAVE_ASINH -DHAVE_ATANH -DHAVE_SNPRINTF -DMOD_TECHDRAW_HANDLE_FACES=1 -DPYCXX_6_2_COMPATIBILITY -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DSALOME_USE_64BIT_IDS -DTechDraw_EXPORTS -D_OCC64 -D_PreComp_ -I%SRC_DIR%\build\src\Mod\TechDraw\App\TechDraw_autogen\include -I%PREFIX%\Library\include\smesh -I%SRC_DIR%\build\src -I%SRC_DIR%\src -I%SRC_DIR%\build -I%SRC_DIR%\build\src\Mod\TechDraw\App -I%SRC_DIR%\src\Mod\TechDraw\App -I%PREFIX%\Library\include -I%PREFIX%\Library\include\opencascade -I%PREFIX%\include -external:I%PREFIX%\Library\include\qt -external:I%PREFIX%\Library\include\qt\QtXmlPatterns -external:I%PREFIX%\Library\include\qt\QtNetwork -external:I%PREFIX%\Library\include\qt\QtCore -external:I%PREFIX%\Library\.\mkspecs\win32-msvc -external:I%PREFIX%\Library\include\qt\QtConcurrent -external:I%PREFIX%\Library\include\qt\QtXml -external:W0 /DWIN32 /D_WINDOWS /W3 /GR  /MP /MD /O2 /Ob2 /DNDEBUG /Zm150 /bigobj /Zi /EHa -std:c++17 /Yu"PreCompiled.h" /FI"D:/bld/freecad_1671212959959/work/build/src/Mod/TechDraw/App/TechDraw.pch" /Fp"D:/bld/freecad_1671212959959/work/build/src/Mod/TechDraw/App/TechDraw.pch" /showIncludes /Fosrc\Mod\TechDraw\App\CMakeFiles\TechDraw.dir\DrawUtil.cpp.obj /Fdsrc\Mod\TechDraw\App\CMakeFiles\TechDraw.dir\ /FS -c %SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): warning C4002: too many arguments for function-like macro invocation 'min'
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2589: '(': illegal token on right side of '::'
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2062: type 'unknown-type' unexpected
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2143: syntax error: missing ';' before '{'
```

**Comment by looooo** [comment]
@wwmayer ok now both windows builds fail with:
```FAILED: src/Mod/TechDraw/App/CMakeFiles/TechDraw.dir/DrawUtil.cpp.obj 
C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DFCAppTechDraw -DHAVE_ACOSH -DHAVE_ASINH -DHAVE_ATANH -DHAVE_SNPRINTF -DMOD_TECHDRAW_HANDLE_FACES=1 -DPYCXX_6_2_COMPATIBILITY -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DSALOME_USE_64BIT_IDS -DTechDraw_EXPORTS -D_OCC64 -D_PreComp_ -I%SRC_DIR%\build\src\Mod\TechDraw\App\TechDraw_autogen\include -I%PREFIX%\Library\include\smesh -I%SRC_DIR%\build\src -I%SRC_DIR%\src -I%SRC_DIR%\build -I%SRC_DIR%\build\src\Mod\TechDraw\App -I%SRC_DIR%\src\Mod\TechDraw\App -I%PREFIX%\Library\include -I%PREFIX%\Library\include\opencascade -I%PREFIX%\include -external:I%PREFIX%\Library\include\qt -external:I%PREFIX%\Library\include\qt\QtXmlPatterns -external:I%PREFIX%\Library\include\qt\QtNetwork -external:I%PREFIX%\Library\include\qt\QtCore -external:I%PREFIX%\Library\.\mkspecs\win32-msvc -external:I%PREFIX%\Library\include\qt\QtConcurrent -external:I%PREFIX%\Library\include\qt\QtXml -external:W0 /DWIN32 /D_WINDOWS /W3 /GR  /MP /MD /O2 /Ob2 /DNDEBUG /Zm150 /bigobj /Zi /EHa -std:c++17 /Yu"PreCompiled.h" /FI"D:/bld/freecad_1671278660860/work/build/src/Mod/TechDraw/App/TechDraw.pch" /Fp"D:/bld/freecad_1671278660860/work/build/src/Mod/TechDraw/App/TechDraw.pch" /showIncludes /Fosrc\Mod\TechDraw\App\CMakeFiles\TechDraw.dir\DrawUtil.cpp.obj /Fdsrc\Mod\TechDraw\App\CMakeFiles\TechDraw.dir\ /FS -c %SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): warning C4002: too many arguments for function-like macro invocation 'min'
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2589: '(': illegal token on right side of '::'
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2062: type 'unknown-type' unexpected
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2143: syntax error: missing ';' before '{'
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2143: syntax error: missing ')' before ';'
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2059: syntax error: ')'
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): error C2059: syntax error: '{'
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(583): error C2601: 'TechDraw::DrawUtil::closestBasis': local function definitions are illegal
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): note: this line contains a '{' which has not yet been matched
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(589): error C2601: 'TechDraw::DrawUtil::closestBasis': local function definitions are illegal
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(553): note: this line contains a '{' which has not yet been matched
%SRC_DIR%\src\Mod\TechDraw\App\DrawUtil.cpp(619): fatal error C1075: '{': no matching token found
[2845/3917] Building CXX object src\Mod\TechDraw\App\CMakeFiles\TechDraw.dir\ShapeExtractor.cpp.obj
[2846/3917] Building CXX object src\Mod\TechDraw\App\CMakeFiles\TechDraw.dir\DrawDimHelper.cpp.obj
```
maybe @WandererFan can help with this issue.

**Comment by looooo** [comment]
seems like this is the problem: https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included

**Comment by looooo** [comment]
next issue: (win/py311)
```
2022-12-18T12:07:01.8576567Z %SRC_DIR%\src\Mod\Fem\Gui\TaskDlgAnalysis.cpp(110): error C2471: cannot update program database '%SRC_DIR%\build\src\Mod\Fem\Gui\CMakeFiles\FemGui.dir\vc140.pdb'
```

**Comment by donovaly** [comment]
Why do you need to build with Precompiled headers for Windows when you have problems?
For the weekly builds we can provide builds without PCH.

More important is that we get the non-Windows builds for the 0.20.2 release. @looooo , can you please upload your MacOS and Linux builds there?:
https://github.com/FreeCAD/FreeCAD/releases/tag/0.20.2

**Comment by wwmayer** [comment]
> Remaining errors:

There is a name collision with std::min and VC's min macro. The solution is to add the define NOMINMAX in boost_regex.hpp before including Windows.h.

> next issue: (win/py311)

Seems like an internal compiler problem. You have to clean the build directory beforehand.

> Why do you need to build with Precompiled headers for Windows when you have problems?
For the weekly builds we can provide builds without PCH.

Things should always compile fine if PCH is on or off.

**Comment by wwmayer** [comment]
5df04f51ce

**Comment by donovaly** [comment]
> Things should always compile fine if PCH is on or off.

You misunderstood me. Sure everything should compile fine.
My point was that we need builds now. While we have them we can fix the other issues. So making non-PCH builds for now.

**Comment by looooo** [comment]
> > Things should always compile fine if PCH is on or off.
> 
> You misunderstood me. Sure everything should compile fine. My point was that we need builds now. While we have them we can fix the other issues. So making non-PCH builds for now.

I did only get rid of the boost error if I build with precomposed headers. That's why I enabled the PCH...

**Comment by looooo** [comment]
> More important is that we get the non-Windows builds for the 0.20.2 release. @looooo , can you please upload your MacOS and Linux builds there?:
> https://github.com/FreeCAD/FreeCAD/releases/tag/0.20.2

I don't have builds for freecad 0.20.2. maybe I have some time to do this in the next couple of days.

**Comment by donovaly** [comment]
I don't have builds for freecad 0.20.2

What is the problem? 
I asked you to prepare some and  the release is therefore on hold for 3 weeks now because without builds we cannot link to them in our download page.

**Comment by looooo** [comment]
> I don't have builds for freecad 0.20.2
> 
> What is the problem? I asked you to prepare some and the release is therefore on hold for 3 weeks now because without builds we cannot link to them in our download page.

https://github.com/conda-forge/freecad-feedstock/pull/79

**Comment by looooo** [comment]
@wwmayer it seems like the boost fix works only for enabled precompiled headers.

**Comment by looooo** [comment]
@wwmayer can you have a look why your fix for boost 1.78 is not working when pch are disabled?

**Comment by wwmayer** [comment]
What are the latest error messages?

**Comment by looooo** [comment]
@wwmayer it's the boost error: 
```
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(200): error C2061: syntax error: identifier 'LCTYPE'
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(217): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(217): error C2737: 'boost::re_detail_500::lctype': constexpr object must be initialized
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(217): error C2737: 'boost::re_detail_500::lctype': constexpr object must be initialized
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(217): error C2146: syntax error: missing ';' before identifier 'locale_idefaultansicodepage'
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(217): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
%PREFIX%\Library\include\boost/regex/v5/w32_regex_traits.hpp(220): error C2039: 'LCMapStringA': is not a member of '`global namespace''
```

**Comment by wwmayer** [comment]
OK, it's still the same error as always. But for which source file does the compiler raise this error?

**Comment by looooo** [comment]
@wwmayer the error occurs in TechDraw:
```
FAILED: src/Mod/TechDraw/App/CMakeFiles/TechDraw.dir/AppTechDrawPy.cpp.obj 
```

I guess that this error didn't occur if pch was enabled. But I am not sure about this.

**Comment by wwmayer** [comment]
I cannot see a reason why it works with PCH enabled and why it fails when disabled.

**Comment by looooo** [comment]
Thanks @wwmayer I will try to include windows.h  via a patch. Maybe this works.

**Comment by looooo** [comment]
@wwmayer The conclusion why it works with pch enabled was because we run into the other issue:
https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included

and you fixed that with:
https://github.com/FreeCAD/FreeCAD/commit/5df04f51ce8e6fd5058d5cced65aa5b5c949fd9f

Now with pch disabled we are stuck again with the boost/regex error. I really have no idea why it works for pch enabled but not with pch disabled. 
There is also this difference when commenting out the ifdef's in the boost_regex file and building with pch disabled:

```
warning C4005: 'NOMINMAX': macro redefinition
```

**Comment by looooo** [comment]
with pch enabled compiling the problematic tech draw file seems to be working:
```
2023-01-07T17:23:38.4347255Z [2861/3939] Building CXX object src\Mod\TechDraw\App\CMakeFiles\TechDraw.dir\AppTechDrawPy.cpp.obj
```
but the build fails somewhere else...

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Comment by looooo** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
