### PR TITLE
Update summary from template

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

Really excited for this to start working for real, it's been a long road! Here's a little fix I found...

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender.

**Comment by looooo** [comment]
thanks for the PR. I will add the commit within the other PR I am currently working on to support osx...

**Comment by bollwyvl** [comment]
Great! Thanks again for all the work. Excited to have a crack at the things
this will enable (cadquery and friends).

>

**Comment by looooo** [comment]
included with: https://github.com/conda-forge/freecad-feedstock/pull/2

**Pull request closed without merging**
